### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Pakeetharan** [sumeshpremraj/saavn-dl#2] opened 2017-06-17 01:36 UTC
Tried both git clone and pip3 install

[Issue Here](http://i.imgur.com/1398TtN.png)

**Comment by sumeshpremraj** [comment] 2017-06-17 05:08
This was caused by hard coded log file path, fixed in commit 3c55afa63de05528552f53a2625c11272676be0c

**Comment by Pakeetharan** [comment] 2017-06-18 06:19
Ohh Thanks
Waiting for the Windows release 👍

**Closed as completed** 2020-10-13 06:16 UTC
